name: Feature Request
description: Suggest an idea for REELSPOT
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        We're always looking for ways to improve REELSPOT!
  - type: textarea
    id: feature-description
    attributes:
      label: Describe the feature
      description: A clear and concise description of what you want to happen.
      placeholder: I want to be able to...
    validations:
      required: true
  - type: textarea
    id: problem-solved
    attributes:
      label: What problem does this solve?
      description: Why would this be useful?
      placeholder: Currently, it's difficult to...
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any alternative solutions or features you've considered.
  - type: textarea
    id: extra
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
